{
  "openapi": "3.0.0",
  "info": {
    "title": "Desafio Share Energy API",
    "description": "This is an API Rent",
    "version": "1.0.0",
    "contact": {
      "name": "Saagas Code",
      "email": "saagas.code@gmail.com",
      "url": "https://portfolio-saagas-code.vercel.app/"
    }
  },
  "paths": {
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Authenticate a user",
        "description": "Authenticate a user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "saagas.code@gmail.com",
                  "password": "hello8819"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email/Username Already Exists"
          }
        }
      }
    },
    "/auth/session": {
      "get": {
        "tags": ["Auth"],
        "summary": "Get the data from the user logged",
        "description": "Get the data from the user logged",
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": ["Users"],
        "summary": "Create a user",
        "description": "Create a new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "fullname": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "saagas",
                  "fullname": "Matthew Oliver",
                  "email": "saagas.code@gmail.com",
                  "password": "hello8819"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email/Username Already Exists"
          }
        }
      },
      "get": {
        "tags": ["Users"],
        "summary": "List all users",
        "description": "List all users if you are a admin",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "description": "Param for Search",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": ["Users"],
        "summary": "List one users",
        "description": "List one users by _id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not FOUND"
          }
        }
      },
      "delete": {
        "tags": ["Users"],
        "summary": "Delete one user",
        "description": "List one users by _id",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "User Not FOUND"
          }
        }
      },
      "patch": {
        "tags": ["Users"],
        "summary": "Update a user",
        "description": "Update a user, you need to be admin or your id in path",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "fullname": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "saagas",
                  "fullname": "Matthew Oliver",
                  "email": "saagas.code@gmail.com",
                  "password": "hello8819"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/clients": {
      "post": {
        "tags": ["Clients"],
        "summary": "Create a client",
        "description": "Create a new client",
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  },
                  "cpf": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "saagas",
                  "email": "saagas.code@gmail.com",
                  "phone": "21988198728",
                  "address": "Rua Alberto",
                  "cpf": "99988877722"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "_id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "address": {
                      "type": "string"
                    },
                    "cpf": {
                      "type": "string"
                    },
                    "user_id": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email or Cpf Already exists"
          }
        }
      },
      "get": {
        "tags": ["Clients"],
        "summary": "List all clients",
        "description": "List all users if you are a admin",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "description": "Param for Search",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "Page for pagination (skip)",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Limit of results",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "clients": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "password": {
                            "type": "string"
                          },
                          "phone": {
                            "type": "string"
                          },
                          "address": {
                            "type": "string"
                          },
                          "cpf": {
                            "type": "string"
                          },
                          "user_id": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "total": {
                      "type": "number"
                    }
                  }
                  
                }
              }
            }
          }
        }
      }
    },
    "/clients/{id}": {
      "get": {
        "tags": ["Clients"],
        "summary": "Find one client by _id",
        "description": "Find one client by _id",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Client ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "password": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "address": {
                        "type": "string"
                      },
                      "cpf": {
                        "type": "string"
                      },
                      "user_id": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cliente não encontrado"
          }
        }
      },
      "delete": {
        "tags": ["Clients"],
        "summary": "Delete one client by _id",
        "description": "Delete one client by _id",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Client ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "Client não encontrado"
          }
        }
      },
      "patch": {
        "tags": ["Clients"],
        "summary": "Update one client",
        "description": "Update one client",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Client ID",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  },
                  "cpf": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "saagas",
                  "email": "saagas.code@gmail.com",
                  "phone": "21988198728",
                  "address": "Rua Alberto",
                  "cpf": "99988877722"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Client Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      },
                      "fullname": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "clients": {
                        "type": "array"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Cliente não encontrado."
          }
        }
      }
    }
  },

  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
